FROM rust:1.97-slim-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config \
    libssl-dev \
    protobuf-compiler \
    libprotobuf-dev \
    curl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-watch

EXPOSE 8080 50051

CMD ["cargo", "watch", "-x", "run"]
