#!/bin/sh
set -eu

APP_DIR=/var/www/html
PORT_VALUE="${PORT:-7860}"

cd "$APP_DIR"

# ─── 1. Nginx configuration ─────────────────────────────────────
#
# Substitute __PORT__ placeholder in the Nginx template so the
# container's listening port can be injected at runtime (required
# for Hugging Face Spaces which uses a dynamic PORT env).

sed "s/__PORT__/${PORT_VALUE}/g" /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf

# ─── 2. Ensure storage directories exist ────────────────────────
#
# Laravel's framework directories must be writable by www-data.
# The Dockerfile creates most of them, but the double-check here
# guards against ephemeral volume mounts that may reset state.

mkdir -p \
    storage/framework/cache \
    storage/framework/sessions \
    storage/framework/views \
    storage/logs \
    bootstrap/cache

chown -R www-data:www-data storage bootstrap/cache

# ─── 3. Bootstrap .env from environment variables ───────────────
#
# On Hugging Face Spaces there is no persistent .env file — all
# configuration comes from Secrets (which become environment
# variables).  We write a .env here so that Laravel's env() helper
# works reliably even when the $_ENV superglobal is incomplete
# (e.g. opcache preloading, some queue workers).
#
# Only the most essential variables for bootstrapping are written;
# the rest are read directly from getenv() by Laravel at runtime
# because php-fpm has `clear_env = no`.  This keeps the .env small
# and avoids hard-coding defaults that might shadow HF Secrets.

if [ ! -f .env ]; then
    echo "No .env found. Generating from environment variables..."

    {
        echo "# Generated by entrypoint.sh at $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
        echo "# Do not edit — values come from Hugging Face Secrets."
        echo ""
        echo "APP_NAME=\"${APP_NAME:-Klass}\""
        echo "APP_ENV=${APP_ENV:-production}"
        echo "APP_KEY=${APP_KEY:-}"
        echo "APP_DEBUG=${APP_DEBUG:-false}"
        echo "APP_URL=${APP_URL:-http://localhost:8000}"
        echo ""
        echo "DB_CONNECTION=${DB_CONNECTION:-pgsql}"
        echo "DB_HOST=${DB_HOST:-db.YOUR_PROJECT_REF.supabase.co}"
        echo "DB_PORT=${DB_PORT:-5432}"
        echo "DB_DATABASE=${DB_DATABASE:-postgres}"
        echo "DB_USERNAME=${DB_USERNAME:-postgres}"
        echo "DB_PASSWORD=${DB_PASSWORD:-}"
        echo "DB_SSLMODE=${DB_SSLMODE:-require}"
        echo ""
        echo "SESSION_DRIVER=${SESSION_DRIVER:-database}"
        echo "SESSION_LIFETIME=${SESSION_LIFETIME:-120}"
        echo ""
        echo "CACHE_STORE=${CACHE_STORE:-database}"
        echo ""
        echo "LOG_CHANNEL=${LOG_CHANNEL:-stderr}"
        echo "LOG_STACK=${LOG_STACK:-single}"
        echo ""
        echo "SANCTUM_STATEFUL_DOMAINS=${SANCTUM_STATEFUL_DOMAINS:-}"
        echo "CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}"
        echo ""
        echo "RUN_MIGRATIONS=${RUN_MIGRATIONS:-false}"
    } > .env

    chown www-data:www-data .env
    echo ".env generated. Set APP_KEY below if still empty."
fi

# ─── 4. Auto-generate APP_KEY if still empty ────────────────────
#
# APP_KEY is critical for Laravel's encryption (session, cookie,
# password reminders, etc.).  If it wasn't provided as a HF Secret
# or in .env, we generate a random one so the app can function.
#
# Note: a generated key is ephemeral — it will change on restart.
# For production, always pin APP_KEY in HF Space Secrets.

if [ -z "${APP_KEY:-}" ]; then
    # Re-read from .env in case it was written above
    if grep -q '^APP_KEY=$' .env 2>/dev/null || ! grep -q '^APP_KEY=[^ ]' .env 2>/dev/null; then
        echo "APP_KEY is empty. Generating a random key..."
        su-exec www-data php artisan key:generate --force
        # Re-export so subsequent commands see it
        APP_KEY=$(grep '^APP_KEY=' .env | cut -d= -f2-)
        export APP_KEY
        echo "APP_KEY generated successfully."
    fi
else
    echo "APP_KEY is set (${APP_KEY:0:10}...)."
fi

# ─── 5. Cache Laravel config, routes, and views ────────────────
#
# Running config:cache bakes .env values into compiled PHP, which
# improves performance significantly.  Controlled by the
# LARAVEL_CACHE_AT_STARTUP flag (default: true).

if [ "${LARAVEL_CACHE_AT_STARTUP:-true}" = "true" ]; then
    echo "Caching Laravel config, routes, and views..."
    rm -f bootstrap/cache/config.php bootstrap/cache/events.php
    rm -f bootstrap/cache/routes-*.php
    rm -f storage/framework/views/*
    su-exec www-data php artisan config:cache
    su-exec www-data php artisan route:cache
    su-exec www-data php artisan view:cache
    echo "Cache built."
fi

# ─── 6. Run database migrations ─────────────────────────────────
#
# Controlled by RUN_MIGRATIONS flag.  Set to "true" on first
# deploy to HF Space (or whenever schema changes need applying).

if [ "${RUN_MIGRATIONS:-false}" = "true" ]; then
    echo "Running database migrations..."
    su-exec www-data php artisan migrate --force
    echo "Migrations complete."
fi

# ─── 7. Start supervisor (nginx + php-fpm) ─────────────────────
#
# Supervisor manages both processes and handles logging.

echo "Starting supervisord..."
exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf