user www-data;
worker_processes auto;

error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /dev/stdout;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    server_tokens off;
    client_max_body_size 25m;
    client_header_buffer_size 16k;
    large_client_header_buffers 4 16k;

    server {
        listen __PORT__ default_server;
        listen [::]:__PORT__ default_server;
        server_name _;
        root /var/www/html/public;
        index index.php index.html;
        charset utf-8;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location = /favicon.ico {
            access_log off;
            log_not_found off;
        }

        location = /robots.txt {
            access_log off;
            log_not_found off;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $realpath_root;
            fastcgi_index index.php;
            fastcgi_pass 127.0.0.1:9000;
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
}